INSERT INTO CONVERT (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('km-meter',*1000);
INSERT INTO CONVERT (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('meter-km',/1000);
INSERT INTO CONVERT (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('inch-meter',*0.025);
INSERT INTO CONVERT (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('meter-inch',/0.025);
INSERT INTO CONVERT (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('foot-meter',*0.3048);
INSERT INTO CONVERT (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('meter-foot',/0.3048);
INSERT INTO CONVERT (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('mile-meterr',*1609.344);
INSERT INTO CONVERT (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('meter-mile',/1609.344);
INSERT INTO CONVERT (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('mm-meter',*0.001);
INSERT INTO CONVERT (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('meter-mm',/0.001);
INSERT INTO CONVERT (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('cm-meter',*0.01);
INSERT INTO CONVERT (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('meter-cm',/0.01);

